name: Build and test

on: [workflow_call]

jobs:
  build_typecheck_test:
    name: Typecheck and test
    uses: ./.github/workflows/build-reusable.yml
    with:
      afterBuild: npm run test
    secrets: inherit